// src/components/Taskbar.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import Tab from "./Tab.svelte";
    import { Sortable } from "@shopify/draggable";

    interface Props {
        tabs: string[];
    }

    let { tabs }: Props = $props();
    let date = $state(new Date());

    setInterval(() => {
        date = new Date();
    }, 1000);

    let container: HTMLElement | undefined = $state();

    onMount(() => {
        if (container) {
            new Sortable(container, { draggable: "span" });
        }
    });
</script>

<div class="navbar bg-body-secondary">
    <div class="container-fluid mx-3">
        <span bind:this={container} class="d-flex align-items-center">
            {#each tabs as tab}
                <Tab {tab} />
            {/each}
        </span>
        <span class="fs-3">{`${date.toLocaleDateString()}`}&nbsp;&nbsp;{`${date.toLocaleTimeString()}`}</span>
    </div>
</div>

// src/components/Taskbar.component.tsx
import { useState, useEffect } from "react";

import { SortableContext } from "@dnd-kit/sortable";

import TabComponent from "./Tab.component";

interface Props {
    tabs: string[]
}

function TaskbarComponent({ tabs }: Props) {
    const [date, setDate] = useState(new Date());

    useEffect(() => {
        const interval = setInterval(() => { setDate(new Date()); }, 1000);
        return () => clearInterval(interval);
    }, []);

    return (
        <div className="navbar bg-body-secondary">
            <div className="container-fluid mx-3">
                <span className="d-flex align-items-center">
                    <SortableContext items={tabs}>
                        {tabs.map((tab, i) => <TabComponent key={i} tab={tab} />)}
                    </SortableContext>
                </span>
                <span className="fs-3">{`${date.toLocaleDateString()}`}&nbsp;&nbsp;{`${date.toLocaleTimeString()}`}</span>
            </div>
        </div>
    );
}

export default TaskbarComponent;
