// src/components/Window.svelte
<script lang="ts">
    export let window: string;
    export let closeApplication: (window: string) => void;

    let fullscreen = false;
</script>

<div class={`card ${fullscreen ? "w-100 h-100" : "w-50 h-75"} position-absolute`}>
    <div class="card-header d-flex justify-content-between align-items-center">
        <span class="display-6">{window}</span>
        <div>
            <button class="btn btn-success">
                <i class="bi bi-dash" />
            </button>
            <button
                on:click={(event) => {
                    fullscreen = !fullscreen;
                }}
                class="btn btn-warning"
            >
                <i class={`bi bi-${fullscreen ? "fullscreen-exit" : "fullscreen"}`} />
            </button>
            <button
                on:click={() => {
                    closeApplication(window);
                }}
                class="btn btn-danger"
            >
                <i class="bi bi-x" />
            </button>
        </div>
    </div>
    <div class="card-body overflow-auto" on:pointerdown={(event) => event.stopPropagation()}>
        <slot />
    </div>
</div>

// src/components/Window.component.tsx
import { PropsWithChildren, MutableRefObject, useState } from 'react';

import { motion, useAnimationControls } from 'framer-motion'

interface Props extends PropsWithChildren {
    window: string
    constraints: MutableRefObject<HTMLDivElement | null>,
    closeApplication: (name: string) => void
}

function WindowComponent({ window, constraints, closeApplication, children }: Props) {
    const [fullscreen, setFullscreen] = useState(false);

    const animationControls = useAnimationControls();

    return (
        <motion.div drag dragConstraints={constraints} dragElastic={false} dragMomentum={false} animate={animationControls} className="position-absolute d-flex flex-column bg-dark border z-2" style={fullscreen ? { width: '100%', height: '100%' } : { width: '50%', height: '75%' }}>
            <div className='navbar bg-body-secondary'>
                <div className='container-fluid'>
                    <span className='display-6'>{window}</span>
                    <div>
                        <button className='btn btn-success me-1'>
                            <i className='bi bi-dash' />
                        </button>
                        <button onClick={() => {
                            animationControls.set({ x: 0, y: 0 });
                            setFullscreen(!fullscreen);
                        }} className='btn btn-warning me-1'>
                            <i className={`bi bi-${fullscreen ? 'fullscreen-exit' : 'fullscreen'}`} />
                        </button>
                        <button onClick={() => { closeApplication(window); }} className='btn btn-danger'>
                            <i className='bi bi-x' />
                        </button>
                    </div>
                </div>
            </div>
            <div className='flex-fill p-4 overflow-auto' onPointerDownCapture={(event) => event.stopPropagation()}>
                {children}
            </div>
        </motion.div>
    );
}

export default WindowComponent;
